### ISSUE TITLE
t/006_solar_longitude.t fails (only today, 2020-02-29?)

### ISSUE THREAD

**Issue by eserte** [lestrrat-p5/DateTime-Astro#9]
Stumbled today on my smoker systems:
```
Invalid day of month (day = 29 - month = 2 - year = 1993)
 at t/DateTime/Astro/Test.pm line 11.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 10.
t/006_solar_longitude.t ....... 
Dubious, test returned 255 (wstat 65280, 0xff00)
All 10 subtests passed 
```
Today's leap day --- probably the test suite fails every four years on 29th of February?

**Comment by jonasbn** [comment]
Well the date: 29th of February 1993, does not exist according to my `cal`

```
$ cal 02 1993
   February 1993
Su Mo Tu We Th Fr Sa
    1  2  3  4  5  6
 7  8  9 10 11 12 13
14 15 16 17 18 19 20
21 22 23 24 25 26 27
28 
```

**Comment by lestrrat** [comment]
ha! I think it's time for me to go back and check

**Comment by lestrrat** [comment]
Hmm, the function `datetime` is present only in the test, so it must be an error originating from the test script and not the actual code. But the date "29" doesn't seem to appear in the test script, I also don't see it attempting to get the current date via localtime/gmtime/DateTime->now... So I'm a bit baffled as to how you got the error...

**Comment by jonasbn** [comment]
Hi @lestrrat 

I was _skimming_ the code yesterday. The file `t/terms.json` holds the date `1993-02-19` and in some of the tests 10 days are added to a a date object. I have however not been able to trace the link between the mentioned test data and the test, which adds 10 days (`t/006_solar_longtitude.t` [line 72](https://metacpan.org/source/DMAKI/DateTime-Astro-1.03/t/006_solar_longitude.t#L72)), since they seem unrelated.

As can be observed from the failing tests from @eserte, which all fail on 2020-02-29, an ability to define today/now in the test suite should make it possible to replicate the the error, which is not currently possible.

**Comment by lestrrat** [comment]
I think I got it. in `t/DateTime/Astro/Test.pm`

```perl
sub datetime {
    my ($y, $m, $d, $H, $M, $S) = @_;
    my $dt = DateTime->today(time_zone => 'UTC');
    $dt->set( year => $y ) if defined $y;
    $dt->set( day => $d ) if defined $d;
    $dt->set( month => $m ) if defined $m;
    $dt->set( hour => $H ) if defined $H;
    $dt->set( minute => $M ) if defined $M;
    $dt->set( second => $S ) if defined $S;
    return $dt;
}
```

`today` becomes 2020-02-29, then we set the year to 1993... oops.

**Comment by lestrrat** [comment]
should be fixed now, but I'm feeling a bit lazy to upload a new release since it only resurfaces every 4 years... :)

**Comment by jonasbn** [comment]
Great! somewhat same issue as in #5
